import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
    return (
        <main className="min-h-screen bg-[#09090F] text-white px-5 pb-16">
            <div className="max-w-[640px] mx-auto">
                {/* Header */}
                <div className="sticky top-0 bg-[#09090F]/95 backdrop-blur-sm pt-12 pb-4 z-10 flex items-center gap-3 border-b border-[#2A2A3D] mb-8">
                    <Link href="/settings" className="p-2 rounded-full hover:bg-[#1C1C28] transition-colors">
                        <ArrowLeft size={20} />
                    </Link>
                    <h1 className="font-['Bricolage_Grotesque'] text-[22px] font-bold">Terms of Service</h1>
                </div>

                <p className="text-[#9898B3] font-['DM_Sans'] text-[14px] mb-8">
                    Last updated: March 25, 2026
                </p>

                <div className="space-y-8 font-['DM_Sans'] text-[15px] leading-relaxed text-[#F2F2FF]">

                    <section className="bg-[#2A1A1A] border border-[#FF6B6B]/30 rounded-[16px] p-4">
                        <p className="text-[#FF6B6B] font-semibold text-[14px]">
                            ⚕️ Not Medical Advice — SnapMacros provides nutrition estimates generated by AI for informational purposes only. It is not a substitute for professional nutritional, dietary, or medical advice. Always consult a qualified healthcare professional for health decisions.
                        </p>
                    </section>

                    <section>
                        <h2 className="font-['Bricolage_Grotesque'] text-[18px] font-semibold mb-3 text-white">1. Acceptance of Terms</h2>
                        <p className="text-[#9898B3]">By downloading, installing, or using SnapMacros (&quot;the App&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the App.</p>
                    </section>

                    <section>
                        <h2 className="font-['Bricolage_Grotesque'] text-[18px] font-semibold mb-3 text-white">2. AI Accuracy Disclaimer</h2>
                        <div className="space-y-3 text-[#9898B3]">
                            <p>Nutrition estimates in SnapMacros are generated by artificial intelligence (Google Gemini) and are <strong className="text-white">estimates only</strong>. They may not be fully accurate due to:</p>
                            <ul className="list-disc list-inside space-y-1">
                                <li>Variation in food preparation methods and ingredients</li>
                                <li>Portion size estimation limitations from photos</li>
                                <li>Limitations of AI vision models</li>
                                <li>Restaurant or branded food variations</li>
                            </ul>
                            <p>SnapMacros is a tool to help you track nutrition generally — not a clinical measurement tool. Do not rely on SnapMacros for medically precise dietary management without professional supervision.</p>
                        </div>
                    </section>

                    <section>
                        <h2 className="font-['Bricolage_Grotesque'] text-[18px] font-semibold mb-3 text-white">3. Eligibility</h2>
                        <p className="text-[#9898B3]">You must be at least 13 years old to use SnapMacros. By using the App, you represent that you meet this age requirement.</p>
                    </section>

                    <section>
                        <h2 className="font-['Bricolage_Grotesque'] text-[18px] font-semibold mb-3 text-white">4. Your Account</h2>
                        <div className="space-y-3 text-[#9898B3]">
                            <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.</p>
                            <p>You may delete your account at any time from Profile &rarr; Account &rarr; Delete Account. Account deletion is permanent and irreversible.</p>
                        </div>
                    </section>

                    <section>
                        <h2 className="font-['Bricolage_Grotesque'] text-[18px] font-semibold mb-3 text-white">5. Acceptable Use</h2>
                        <div className="space-y-3 text-[#9898B3]">
                            <p>You agree not to:</p>
                            <ul className="list-disc list-inside space-y-1">
                                <li>Use the App to harm yourself or others</li>
                                <li>Attempt to reverse-engineer, hack, or abuse the App or its APIs</li>
                                <li>Submit content that is illegal, abusive, or violates others&apos; rights</li>
                                <li>Use the App for any commercial purpose without written permission</li>
                            </ul>
                        </div>
                    </section>

                    <section>
                        <h2 className="font-['Bricolage_Grotesque'] text-[18px] font-semibold mb-3 text-white">6. Intellectual Property</h2>
                        <p className="text-[#9898B3]">SnapMacros and its content, including the Chip mascot, design, and code, are owned by SnapMacros and protected by applicable intellectual property laws. You may not reproduce or distribute any part of the App without written permission.</p>
                    </section>

                    <section>
                        <h2 className="font-['Bricolage_Grotesque'] text-[18px] font-semibold mb-3 text-white">7. Disclaimers & Limitation of Liability</h2>
                        <div className="space-y-3 text-[#9898B3]">
                            <p>THE APP IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND. SNAPMACROS DOES NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT AI ESTIMATES WILL BE ACCURATE.</p>
                            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, SNAPMACROS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE APP.</p>
                        </div>
                    </section>

                    <section>
                        <h2 className="font-['Bricolage_Grotesque'] text-[18px] font-semibold mb-3 text-white">8. Termination</h2>
                        <p className="text-[#9898B3]">We reserve the right to suspend or terminate your account if you violate these Terms. You may terminate your account at any time by deleting it from the App.</p>
                    </section>

                    <section>
                        <h2 className="font-['Bricolage_Grotesque'] text-[18px] font-semibold mb-3 text-white">9. Changes to Terms</h2>
                        <p className="text-[#9898B3]">We may modify these Terms from time to time. Continued use of the App after changes constitutes acceptance of the updated Terms.</p>
                    </section>

                    <section>
                        <h2 className="font-['Bricolage_Grotesque'] text-[18px] font-semibold mb-3 text-white">10. Contact</h2>
                        <p className="text-[#9898B3]">Questions about these Terms? Contact us at: <a href="mailto:support@snapmacros.app" className="text-[#4F9EFF]">support@snapmacros.app</a></p>
                    </section>

                </div>
            </div>
        </main>
    );
}
